!!it.unibo.model.level.loader.skeleton.level.LevelSkeletonImpl
lives: 3
width: 500
height: 560
levelNumber: 1
pad:
    x: 200
    y: 500
balls:
  - x: 240
    y: 300
    paceX: 0
    paceY: 200
    ballType: "NORMAL"
    id: 1
bricks:
  - x: 30
    y: 50
    type: "RED"
  - x: 90
    y: 50
    type: "ORANGE"
  - x: 150
    y: 50
    type: "ORANGE"
  - x: 210
    y: 50
    type: "YELLOW"
  - x: 30
    y: 100
    type: "ORANGE"
  - x: 90
    y: 100
    type: "RED"
  - x: 150
    y: 100
    type: "RED"
  - x: 210
    y: 100
    type: "YELLOW"
  - x: 30
    y: 150
    type: "YELLOW"
  - x: 400
    y: 150
    type: "GREEN"
  - x: 150
    y: 150
    type: "GREEN"
  - x: 210
    y: 150
    type: "RED"
  - x: 30
    y: 200
    type: "BLUE"
  - x: 90
    y: 200
    type: "PURPLE"
  - x: 150
    y: 200
    type: "INDESTRUCTIBLE"
